# ----------------------------------------------------
# 各种图像干扰效果的参数配置文件
# ----------------------------------------------------

# 1. 复杂污损 (Complex Smudge)
smudge_complex:
  num_blotches_min: 5      # 构成一个污渍团的最小污渍数量
  num_blotches_max: 8      # ...最大数量
  radius_min: 50           # 单个小污渍的最小半径
  radius_max: 150           # ...最大半径
  offset_max: 40           # 小污渍相对于中心的偏移量
  offset_max_angular: 0.1 # for 3d
  blur_kernel_min: 11      # 污渍遮罩的最小模糊核大小 (必须是奇数)
  blur_kernel_max: 31      # ...最大模糊核大小 (必须是奇数)
  alpha_min: 0.7          # 污渍的最小不透明度
  alpha_max: 0.9          # ...最大不透明度

# 3. 眩光 (Glare)
glare:
  radius_min: 50           # 眩光半径的最小值
  radius_max: 80          # ...最大值
  brightness_min: 1.5      # 眩光的最小亮度
  brightness_max: 1.6      # ...最大亮度
  blur_amount_min: 51     # 眩光模糊核的最小尺寸 (必须是奇数)
  blur_amount_max: 151     # ...最大尺寸 (必须是奇数)
  area_contribution_ratio: 1  # 面积贡献比例：这个比例乘以眩光遮罩的原始面积，得到其在总面积计算中的“有效面积”。

# 4. 局部模糊点 (Local Blur Spots) 
local_blur_spots:
  num_spots_min: 5         # 模糊点的最小数量
  num_spots_max: 10        # ...最大数量
  radius_min: 100           # 模糊点的最小半径
  radius_max: 150           # ...最大半径
  # 用于模糊图像本身的核大小，值越大，模糊区域越朦胧
  image_blur_kernel_min: 301 # (必须是奇数)
  image_blur_kernel_max: 401 # (必须是奇数)
  # 用于羽化模糊区域边缘的核大小，值越大，边缘越柔和
  mask_blur_kernel_min: 21  # (必须是奇数)
  mask_blur_kernel_max: 91  # (必须是奇数)

# 全局控制参数
global_control:
  min_area_ratio: 0.2      # 污损总面积占图像的最小比例
  max_area_ratio: 0.3      # ...最大比例
  max_iterations: 50       # 为达到目标面积，最多尝试添加多少个效果元素